### ISSUE TITLE
LICENSE file needed for proper attribution and clear guidance on how to work with the file

### ISSUE THREAD

**Issue by ceszare** [huy-nguyen/redux-observable-marble-diagrams#4]
I would like to borrow the code under testUtils to allow me to mock failures while testing rxjs marble diagrams. Unfortunately, I couldn't find a `LICENSE` file to do so. There is also no reference to the license on `package.json`.

Would it be possible for you to establish a `LICENSE` to determine if we could use the code?

Thanks!
Cesar

**Comment by huy-nguyen** [comment]
Fixed by #5.
